simple_blog/App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list')
]

simple_blog/App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('signin/', views.login_page, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.password_change, name='password_change'),
    path('change-profile-image', views.add_pro_pro, name='add_pro_pic')
]

simple_blog/simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

simple_blog/App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    author = models.ForeignKey(User, related_name='post_author', on_delete=models.CASCADE)
    blog_title = models.CharField(max_length=300, verbose_name='Put a Title')
    slug = models.SlugField(max_length=300, unique=True)
    blog_content = models.TextField(verbose_name="What is on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Blog Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.blog_title
    


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_comment")
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=False)



class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="liked_blog")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_user')

simple_blog/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

simple_blog/App_Blog/views.py
from django.shortcuts import render

def blog_list(request):
    return render(request, 'App_Blog/blog_list.html', context={})

simple_blog/App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.form import SignUpForm, UserProfileChange, ProfilePic

def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registered':registered}
    return render(request, 'App_Login/sign_up.html', context=dict)





def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'App_Login/login.html', context={'form':form})



@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:signin'))



@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})



@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'App_Login/change_profile.html', context={'form':form})



@login_required
def password_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_login/password_change.html', context={'form':form, 'changed':changed})
        


@login_required
def add_pro_pro(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})

simple_blog/simple_blog/views.py
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse

def index(request):
    return HttpResponseRedirect(reverse('App_Blog:blog_list'))

simple_blog/templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% block title %}  Home  {% endblock %}

{% block body_block %}
<h1> I am a blog list page</h1>

{% endblock %}

simple_blog/templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Change User Profile {% endblock %}


{% block body_block %}
<h2>User Profile Change</h2>

<form method="post">
    {{ form | crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Change</button>
</form>

{% endblock %}

simple_blog/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}  Login Page {% endblock %}



{% block body_block %}
<h2>Login To Your Account</h2>

<form method="post">
    {{ form | crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>

{% endblock %}

simple_blog/templates/App_Login/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}  Password Change Page {% endblock %}

{% block body_block %}

{% if changed %}
<div class="alert alert-success">
    Password Changed Successfully
</div>
{% endif %}


<h2>Password Change </h2>

<form method="post">
    {{ form | crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Change Password</button>
</form>

{% endblock %}

simple_blog/templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}  Profile Picture Update {% endblock %}



{% block body_block %}
<h2>Add Your Profile Picture</h2>

<form method="post" enctype="multipart/form-data">
    {{ form | crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Add Picture</button>
</form>

{% endblock %}

simple_blog/templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title %}  Profile Page {% endblock %}



{% block body_block %}
<h2>Your Profile</h2>

{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="120px">
{% else %}
<img src="/media/default.jpeg" class="rounded-circle" width="120px">
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% endif %}

<br>
<br>
<br>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name: {{ user.first_name }} {{ user.last_name }} </p>

<a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>

{% endblock %}

simple_blog/templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}  Create New Account  {% endblock %}

{% block body_block %}
{% if registered %}
<div class="alert alert-success">
    Account Create Successfully <a href="{% url 'App_Login:signin' %}">Login Here</a>
</div>
{% else %}


<h2>Create New Account</h2>
<form method='post'>
    {{ form | crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Already have an account? <a href="{% url 'App_Login:signin' %}">Login Here</a></p>

{% endif %}
{% endblock %}

simple_blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>
        {% block title %}
            Blogs page
        {% endblock %}
    </title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>

    {% if user.is_authenticated %}      
            
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
            </li>

    {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'App_Login:signin' %}">Login</a>
            </li>
    {% endif %}

        </ul>
    </nav>


    <div class="container" style="padding-top:20px">

    {% block body_block %}

    {% endblock %}

    </div>





    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>